[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python backup_manager.py && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[mounts]]
source = "data"
destination = "/data" 