"""add last_updated field

Revision ID: e0239a104393
Revises: 
Create Date: 2025-06-06 11:32:47.045175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0239a104393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
